version: "3"
services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      ENABLE_AUTOSTOP: TRUE
      INIT_MEMORY: 1G
      MAX_MEMORY: 4G
      EULA: "TRUE"
      TYPE: "FORGE"
      VERSION: "1.20.1"
      LEVEL: "Yep - copie"
      USE_MODPACK_START_SCRIPT: false
      CUSTOM_FORGE: forge-1.20.1-47.3.0-server.jar.lnk
      GENERIC_PACK: server_pack.zip
      SERVER_NAME: Create Maxime 1.20.1
      PLAYER_IDLE_TIMEOUT: 600
      STOP_SERVER_ANNOUNCE_DELAY: 60
    volumes:
      - ./data:/data
      
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
volumes:
  portainer_data: